/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : string,
  'name' : string,
  'description' : string,
}
export interface IndustryType {
  'id' : string,
  'categoryId' : string,
  'name' : string,
  'description' : string,
}
export interface Subtype {
  'id' : string,
  'salaryMidLevel' : number,
  'roleTypeContext' : string,
  'typicalActivities' : Array<string>,
  'globalContext' : string,
  'name' : string,
  'typeId' : string,
  'description' : string,
  'salarySeniorLevel' : number,
  'valueChainDescription' : string,
  'employmentPercentage' : number,
  'totalWorkersEstimate' : bigint,
  'typicalRoles' : Array<string>,
  'salaryEntryLevel' : number,
}
export interface _SERVICE {
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getSubtypeDetail' : ActorMethod<[string], Subtype>,
  'getSubtypesByType' : ActorMethod<[string], Array<Subtype>>,
  'getTypesByCategory' : ActorMethod<[string], Array<IndustryType>>,
  'searchSubtypes' : ActorMethod<[string], Array<Subtype>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];