/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Subtype = IDL.Record({
  'id' : IDL.Text,
  'salaryMidLevel' : IDL.Float64,
  'roleTypeContext' : IDL.Text,
  'typicalActivities' : IDL.Vec(IDL.Text),
  'globalContext' : IDL.Text,
  'name' : IDL.Text,
  'typeId' : IDL.Text,
  'description' : IDL.Text,
  'salarySeniorLevel' : IDL.Float64,
  'valueChainDescription' : IDL.Text,
  'employmentPercentage' : IDL.Float64,
  'totalWorkersEstimate' : IDL.Nat,
  'typicalRoles' : IDL.Vec(IDL.Text),
  'salaryEntryLevel' : IDL.Float64,
});
export const IndustryType = IDL.Record({
  'id' : IDL.Text,
  'categoryId' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getSubtypeDetail' : IDL.Func([IDL.Text], [Subtype], ['query']),
  'getSubtypesByType' : IDL.Func([IDL.Text], [IDL.Vec(Subtype)], ['query']),
  'getTypesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IndustryType)],
      ['query'],
    ),
  'searchSubtypes' : IDL.Func([IDL.Text], [IDL.Vec(Subtype)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Subtype = IDL.Record({
    'id' : IDL.Text,
    'salaryMidLevel' : IDL.Float64,
    'roleTypeContext' : IDL.Text,
    'typicalActivities' : IDL.Vec(IDL.Text),
    'globalContext' : IDL.Text,
    'name' : IDL.Text,
    'typeId' : IDL.Text,
    'description' : IDL.Text,
    'salarySeniorLevel' : IDL.Float64,
    'valueChainDescription' : IDL.Text,
    'employmentPercentage' : IDL.Float64,
    'totalWorkersEstimate' : IDL.Nat,
    'typicalRoles' : IDL.Vec(IDL.Text),
    'salaryEntryLevel' : IDL.Float64,
  });
  const IndustryType = IDL.Record({
    'id' : IDL.Text,
    'categoryId' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getSubtypeDetail' : IDL.Func([IDL.Text], [Subtype], ['query']),
    'getSubtypesByType' : IDL.Func([IDL.Text], [IDL.Vec(Subtype)], ['query']),
    'getTypesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IndustryType)],
        ['query'],
      ),
    'searchSubtypes' : IDL.Func([IDL.Text], [IDL.Vec(Subtype)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };